# Generated by Django 2.2.6 on 2019-10-26 21:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='content_en',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Content EN'),
        ),
        migrations.AddField(
            model_name='question',
            name='content_es',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Content ES'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_en',
            field=models.CharField(default='', max_length=200, verbose_name='Question EN'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_es',
            field=models.CharField(default='', max_length=200, verbose_name='Question ES'),
        ),
    ]
