# Generated by Django 2.2.6 on 2019-10-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20191026_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_en',
            field=models.CharField(max_length=200, verbose_name='Question EN'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_es',
            field=models.CharField(max_length=200, verbose_name='Question ES'),
        ),
    ]
