# Generated by Django 2.2.6 on 2019-10-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_model_quote_turns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_quote',
            old_name='name',
            new_name='day',
        ),
        migrations.RemoveField(
            model_name='model_quote',
            name='date',
        ),
        migrations.RemoveField(
            model_name='model_quote',
            name='email',
        ),
        migrations.RemoveField(
            model_name='model_quote',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='model_quote',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='model_quote',
            name='turn',
        ),
        migrations.AddField(
            model_name='model_quote',
            name='turn',
            field=models.ManyToManyField(related_name='get_turns', to='contact.Turns', verbose_name='Turns'),
        ),
    ]
