# Generated by Django 2.2.6 on 2019-10-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20191021_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
