# Generated by Django 2.2.6 on 2019-10-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_model_quote_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turns',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Turn'),
        ),
    ]
