# Generated by Django 2.2.6 on 2019-10-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20191021_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_quote',
            name='day_code',
            field=models.IntegerField(default=0, verbose_name='Code'),
        ),
    ]
