# Generated by Django 2.2.6 on 2019-10-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_model_quote_day_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model_quote',
            options={'ordering': ['created'], 'verbose_name': 'Quote Model', 'verbose_name_plural': 'Quotes Models'},
        ),
    ]
