# Generated by Django 2.2.6 on 2019-10-26 21:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191011_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Name EN'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Name ES'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Content ES'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(default='', max_length=200, verbose_name='Title EN'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es',
            field=models.CharField(default='', max_length=200, verbose_name='Title ES'),
        ),
    ]
