# Generated by Django 2.2.6 on 2019-10-26 21:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191026_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name EN'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name ES'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=ckeditor.fields.RichTextField(verbose_name='Content ES'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, verbose_name='Title EN'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_es',
            field=models.CharField(max_length=200, verbose_name='Title ES'),
        ),
    ]
