# Generated by Django 2.2.6 on 2019-10-26 22:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191026_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_es',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Content ES'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=ckeditor.fields.RichTextField(verbose_name='Content EN'),
        ),
    ]
