# Generated by Django 2.2.6 on 2019-10-26 22:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191026_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_es',
            field=ckeditor.fields.RichTextField(verbose_name='Content ES'),
        ),
    ]
