# Generated by Django 2.2.6 on 2019-10-10 10:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Who_We_Are',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Who we are',
                'verbose_name_plural': 'Who we are',
            },
        ),
        migrations.CreateModel(
            name='WorkTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Title')),
                ('job', models.CharField(max_length=200, verbose_name='Job')),
                ('info', ckeditor.fields.RichTextField(verbose_name='Info')),
                ('photo', models.ImageField(upload_to='our_team', verbose_name='Photo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Associates',
                'verbose_name_plural': 'Work Team',
                'ordering': ['-created'],
            },
        ),
    ]
