# Generated by Django 2.2.6 on 2019-10-10 10:52

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('our_team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workteam',
            name='email',
            field=models.EmailField(default=False, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='workteam',
            name='phone_number',
            field=phone_field.models.PhoneField(default=False, max_length=50, verbose_name='Phone Number'),
        ),
    ]
