# Generated by Django 2.2.6 on 2019-10-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_team', '0002_auto_20191010_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='who_we_are',
            name='title',
            field=models.CharField(default='Who We Are', editable=False, max_length=150, verbose_name='Who We Are'),
        ),
    ]
