# Generated by Django 2.2.6 on 2019-10-10 11:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('our_team', '0003_who_we_are_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workteam',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone Number'),
        ),
    ]
