# Generated by Django 2.2.6 on 2019-10-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_team', '0004_auto_20191010_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='workteam',
            name='lastname',
            field=models.CharField(default=False, max_length=200, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='workteam',
            name='name',
            field=models.CharField(default=False, max_length=200, verbose_name='Name'),
        ),
    ]
