# Generated by Django 2.2.6 on 2019-10-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_team', '0005_auto_20191010_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workteam',
            name='lastname',
            field=models.CharField(max_length=200, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='workteam',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
