# Generated by Django 2.2.6 on 2019-10-26 21:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_team', '0006_auto_20191010_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='who_we_are',
            name='content',
        ),
        migrations.RemoveField(
            model_name='workteam',
            name='info',
        ),
        migrations.RemoveField(
            model_name='workteam',
            name='job',
        ),
        migrations.AddField(
            model_name='who_we_are',
            name='content_en',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Content EN'),
        ),
        migrations.AddField(
            model_name='who_we_are',
            name='content_es',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Content ES'),
        ),
        migrations.AddField(
            model_name='workteam',
            name='info_en',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Info EN'),
        ),
        migrations.AddField(
            model_name='workteam',
            name='info_es',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Info ES'),
        ),
        migrations.AddField(
            model_name='workteam',
            name='job_en',
            field=models.CharField(default='', max_length=200, verbose_name='Job EN'),
        ),
        migrations.AddField(
            model_name='workteam',
            name='job_es',
            field=models.CharField(default='', max_length=200, verbose_name='Job ES'),
        ),
        migrations.AlterField(
            model_name='workteam',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Phone Number'),
        ),
    ]
