# Generated by Django 2.2.6 on 2019-10-26 21:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_team', '0007_auto_20191026_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workteam',
            name='info_en',
            field=ckeditor.fields.RichTextField(verbose_name='Info EN'),
        ),
        migrations.AlterField(
            model_name='workteam',
            name='info_es',
            field=ckeditor.fields.RichTextField(verbose_name='Info ES'),
        ),
        migrations.AlterField(
            model_name='workteam',
            name='job_en',
            field=models.CharField(max_length=200, verbose_name='Job EN'),
        ),
        migrations.AlterField(
            model_name='workteam',
            name='job_es',
            field=models.CharField(max_length=200, verbose_name='Job ES'),
        ),
    ]
